version: "3.9"
services:
  database:
    image: postgres
    env_file: ./postgres-config
    secrets:
      - postgres-password
    networks:
      - bot-database
      - tweet-database
    volumes:
      - pgdata:/var/lib/postgresql/data

  tweet:
    build:
      context: .
      dockerfile: tweet.Dockerfile
    env_file:
      - ./postgres-config
    depends_on:
      - "database"
    networks:
      - tweet-database
    secrets:
      - postgres-password
      - telegram-token
      - telegram_api_hash
      - telegram_api_id
      - telegram_phone
      - twitter_access_token
      - twitter_api_key
      - twitter_api_secret
      - twitter_secret_token
      - imgur_access_token
      - imgur_account_id
      - imgur_client_id
      - imgur_client_secret
      - imgur_refresh_token
      - instagram_access_token
      - instagram_user_id


secrets:
  postgres-password:
    file: ./secrets/postgres-password
  telegram-token:
    file: ./secrets/telegram-token
  telegram_api_hash:
    file: ./secrets/telegram_api_hash
  telegram_api_id:
    file: ./secrets/telegram_api_id
  telegram_phone:
    file: ./secrets/telegram_phone
  twitter_access_token:
    file: ./secrets/twitter_access_token
  twitter_api_key:
    file: ./secrets/twitter_api_key
  twitter_api_secret:
    file: ./secrets/twitter_api_secret
  twitter_secret_token:
    file: ./secrets/twitter_secret_token
  imgur_access_token:
    file: ./secrets/imgur_access_token
  imgur_account_id:
    file: ./secrets/imgur_account_id
  imgur_client_id:
    file: ./secrets/imgur_client_id
  imgur_client_secret:
    file: ./secrets/imgur_client_secret
  imgur_refresh_token:
    file: ./secrets/imgur_refresh_token
  instagram_access_token:
    file: ./secrets/instagram_access_token
  instagram_user_id:
    file: ./secrets/instagram_user_id



networks:
  bot-database:
  tweet-database:

volumes:
  pgdata:
